services:
  app:
    # build: . # Uncomment to build locally
    image: av512406/school-erp-app:latest
    container_name: school_erp_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://school_erp:school_erp_pass@postgres:5432/school_erp
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:16
    container_name: school_erp_db
    environment:
      POSTGRES_USER: school_erp
      POSTGRES_PASSWORD: school_erp_pass
      POSTGRES_DB: school_erp
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U school_erp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: